Controllers/ColoresController.cs
using Google.Cloud.Firestore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ps_mosquito_asp.Models;
using System.Data;

namespace ps_mosquito_asp.Controllers
{
    [Authorize(Roles = "Administrador, R")]
    public class ColoresController : Controller
    {
        public ColoresController()
        {
            //string jsonPath = @"C:\\Users\\brianlml\\Desktop\\ps_mosquito_asp\\mosquitobd-202b0-firebase-adminsdk-7c4jx-8814777652.json";
            string baseDirectory = AppDomain.CurrentDomain.BaseDirectory;
            string jsonFileName = "mosquitobd-202b0-firebase-adminsdk-7c4jx-8814777652.json";
            string jsonPath = Path.Combine(baseDirectory, jsonFileName);
            Environment.SetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS", jsonPath);
        }
        public IActionResult Create()
        {
            return View();
        }

        public async Task<IActionResult> Index()
        {
            var db = FirestoreDb.Create("mosquitobd-202b0");
            var colors = new List<ColorModel>();
            CollectionReference colorsRef = db.Collection("colors");
            QuerySnapshot snapshot = await colorsRef.GetSnapshotAsync();
            foreach (DocumentSnapshot document in snapshot.Documents)
            {
                if (document.Exists)
                {
                    var data = document.ToDictionary();
                    var color = new ColorModel
                    {
                        id = document.Id,
                        color = data.ContainsKey("color") ? data["color"].ToString() : null,
                        name = data.ContainsKey("name") ? data["name"].ToString() : null,
                        description = data.ContainsKey("description") ? data["description"].ToString() : null,
                    };
                    colors.Add(color);
                }
            }
            return View(colors);
        }

        //POST - CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ColorModel colorPost)
        {
            if (ModelState.IsValid)
            {
                var db = FirestoreDb.Create("mosquitobd-202b0");
                CollectionReference colorsRef = db.Collection("colors");
                Dictionary<string, object> data1 = new Dictionary<string, object>()
                {
                    {"color", colorPost.color},
                    {"name", colorPost.name},
                    {"description", colorPost.description}
                };
                await colorsRef.AddAsync(data1);
                return RedirectToAction(nameof(Index));
            }
            return View(colorPost);
        }
        public async Task<IActionResult> EditColor(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }
            var db = FirestoreDb.Create("mosquitobd-202b0");
            DocumentReference docRef = db.Collection("colors").Document(id);
            DocumentSnapshot snapshot = await docRef.GetSnapshotAsync();
            if (!snapshot.Exists)
            {
                return NotFound();
            }
                var data = snapshot.ToDictionary();
                var color = new ColorModel
                {
                    id = id,
                    color = data.ContainsKey("color") ? data["color"].ToString() : null,
                    name = data.ContainsKey("name") ? data["name"].ToString() : null,
                    description = data.ContainsKey("description") ? data["description"].ToString() : null,
                };
                return View(color);
        }

        //POST - EDIT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditColor(string id, ColorModel colorPost)
        {
            if (id != colorPost.id)
            {
                return NotFound();
            }
            
            if (ModelState.IsValid)
            {
                try
                {
                    var db = FirestoreDb.Create("mosquitobd-202b0");
                    DocumentReference docRef = db.Collection("colors").Document(colorPost.id);
                    Dictionary<string, object> updates = new Dictionary<string, object>()
                {
                    {"color", colorPost.color},
                    {"name", colorPost.name},
                    {"description", colorPost.description}
                };
                    await docRef.UpdateAsync(updates);
                }
                catch (Exception)
                {
                    ModelState.AddModelError("", "Ocurrió un error al actualizar el color.");
                    return View(colorPost);
                }
               
                return RedirectToAction(nameof(Index));
            }
            return View(colorPost);
        }

        //GET - DELETE
        public async Task<IActionResult> DeleteColor(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var db = FirestoreDb.Create("mosquitobd-202b0");
            DocumentReference docRef = db.Collection("colors").Document(id);
            DocumentSnapshot snapshot = await docRef.GetSnapshotAsync();
            if (snapshot.Exists)
            {
                var data = snapshot.ToDictionary();
                var color = new ColorModel
                {
                    id = id,
                    color = data.ContainsKey("color") ? data["color"].ToString() : null,
                    name = data.ContainsKey("name") ? data["name"].ToString() : null,
                    description = data.ContainsKey("description") ? data["description"].ToString() : null,
                };
                return await DeleteConfirmed(id);
                
            }
            return NotFound();
        }
        //POST - DELETE
        [HttpPost, ActionName("DeleteColor")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            try
            {
                var db = FirestoreDb.Create("mosquitobd-202b0");
                DocumentReference docRef = db.Collection("colors").Document(id);
                await docRef.DeleteAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {

                ModelState.AddModelError("", "Ocurrió un error al eliminar el color.");
                return View();
            }
            
        }

    }
}

Controllers/ZonasController.cs
using Google.Cloud.Firestore;
using Google.Type;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using ps_mosquito_asp.Models;
using LatLng = ps_mosquito_asp.Models.LatLng;
using System.Linq;
using Microsoft.AspNetCore.Authorization;

namespace ps_mosquito_asp.Controllers
{
    [Authorize(Roles = "Administrador, R")]
    public class ZonasController : Controller
    {
        //FirestoreDb? _db;
        public ZonasController (){

            //string projectId = "mosquitobd-202b0";
            //string jsonPath = @"C:\Users\HP\Desktop\Mosquito\PS_MOSQUITO_ASP\mosquitobd-202b0-firebase-adminsdk-7c4jx-8814777652.json";
            //string jsonPath = @"C:\\Users\\brianlml\\Desktop\\ps_mosquito_asp\\mosquitobd-202b0-firebase-adminsdk-7c4jx-8814777652.json";
            string baseDirectory = AppDomain.CurrentDomain.BaseDirectory;
            string jsonFileName = "mosquitobd-202b0-firebase-adminsdk-7c4jx-8814777652.json";
            string jsonPath = Path.Combine(baseDirectory, jsonFileName);
            Environment.SetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS", jsonPath);
            //FirestoreDb _db = FirestoreDb.Create(projectId);
        }

        public ActionResult Index()
        {
            var _db = FirestoreDb.Create("mosquitobd-202b0");

            // Accede a la colección "users" en Firestore
            CollectionReference usersRef = _db.Collection("users");
            // Realiza una consulta para obtener los usuarios con "role" igual a "Supervisor"
            Query query = usersRef.WhereEqualTo("role", "Supervisor");
            QuerySnapshot userSnapshot = query.GetSnapshotAsync().Result;

            // Crea una lista de usuarios que cumplen con el filtro
            var supervisors = new List<UserModel>();

            foreach (DocumentSnapshot document in userSnapshot.Documents)
            {
                if (document.Exists)
                {
                    // Obtiene los campos del documento Firestore
                    var data = document.ToDictionary();
                    // Crea un nuevo objeto UserModel y asigna los valores manualmente
                    var user = new UserModel
                    {
                        id = document.Id,
                        name = data.ContainsKey("name") ? data["name"].ToString() : null,
                        // Ajusta el nombre del campo según corresponda
                        // Asigna otros campos aquí
                        lastname = data.ContainsKey("lastname") ? data["lastname"].ToString() : null,
                        ci = data.ContainsKey("ci") ? data["ci"].ToString() : null,
                        role = data.ContainsKey("role") ? data["role"].ToString() : null,
                        position = data.ContainsKey("position") ? data["position"].ToString() : null,
                        email = data.ContainsKey("email") ? data["email"].ToString() : null,
                        password = data.ContainsKey("password") ? data["password"].ToString() : null
                    };
                    supervisors.Add(user);
                }
            }

            // Accede a la colección "colors" en Firestore
            CollectionReference colorsRef = _db.Collection("colors");
            Query colorsQuery = colorsRef;
            QuerySnapshot colorsSnapshot = colorsQuery.GetSnapshotAsync().Result;

            // Crea una lista de nombres de colores
            var colorNamesAndIds = new List<Tuple<string, string>>();

            foreach (DocumentSnapshot colorDocument in colorsSnapshot.Documents)
            {
                if (colorDocument.Exists)
                {
                    var colorData = colorDocument.ToDictionary();
                    var colorName = colorData.ContainsKey("name") ? colorData["name"].ToString() : null;
                    var colorId = colorDocument.Id; // Obtener el ID del documento
                    colorNamesAndIds.Add(new Tuple<string, string>(colorName, colorId));
                }
            }

            // Almacena la lista de nombres de colores en un ViewBag
            ViewBag.ColorNamesAndIds = colorNamesAndIds;

            return View(supervisors);
        }


        [HttpPost]
        public async Task<ActionResult> AssignTasks(string SupervisorId, int cantidadMax, string cityName, string polygonCoords, string tipoColorId)
        {
            if (SupervisorId != null)
            {
                List<LatLng>? coordinates = JsonConvert.DeserializeObject<List<LatLng>>(polygonCoords);
                var coordinatesDictList = coordinates?.Select(coord => new Dictionary<string, double>
        {
            {"Lat", coord.Lat},
            {"Lng", coord.Lng}
        }).ToList();

                var db = FirestoreDb.Create("mosquitobd-202b0");
                CollectionReference tasksRef = db.Collection("task");

                // Crea un nuevo objeto de tarea con los campos necesarios
                var newTask = new
                {
                    Estado = "Pendiente",
                    CantidadTareasRealizadas = 0,
                    TipoColor = tipoColorId,
                    SupervisorId = SupervisorId,
                    CantidadMax = cantidadMax,
                    Zona = cityName,
                    coordenadas = coordinatesDictList
                };

                // Agrega la tarea a Firestore y obtén el ID de la tarea creada
                DocumentReference addedTaskRef = await tasksRef.AddAsync(newTask);
                string taskId = addedTaskRef.Id;

                // Actualiza el documento con el ID de la tarea
                await addedTaskRef.UpdateAsync("IDtarea", taskId);

                return View();
            }
            else
            {
                ModelState.AddModelError("SupervisorId", "Debes seleccionar un supervisor.");
                return View();
            }
        }
    }
}

Views/Shared/_Dashboard.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ps_mosquito_asp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ps_mosquito_asp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                    <img src="/logo_mosquito.png" alt="logo_mosquito" style="width:32px; height:32px;" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav mx-auto">
                        <!-- Utiliza la clase mx-auto para centrar los elementos -->
                        <li class="nav-item">
                            <a class="nav-link   " aria-current="page" asp-area="" asp-controller="Account" asp-action="Users">Usuarios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Reporte" asp-action="Index">Reporte</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Zonas" asp-action="Index">Zonas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Colores" asp-action="Index">Colores</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        <!-- Utiliza la clase ml-auto para alinear a la derecha -->
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Account" asp-action="LogOut" id="navbarDropdownMenuLink">
                                Cerrar Sesion
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2023 - PS MOSQUITO
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ps_mosquito_asp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ps_mosquito_asp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                    <img src="/logo_mosquito.png" alt="logo_mosquito" style="width:32px; height:32px;" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav ms-auto">
                            <!-- Utiliza la clase mx-auto para centrar los elementos -->
                            @if (User.Identity.IsAuthenticated)
                            {
                            <li class="nav-item">
                                <a class="nav-link   " aria-current="page" asp-area="" asp-controller="Account" asp-action="Users">Usuarios</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Reporte" asp-action="Index">Reporte</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Zonas" asp-action="Index">Zonas</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Colores" asp-action="Index">Colores</a>
                            </li>
                            }
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Ingresar a la Web
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">

                                @if (!User.Identity.IsAuthenticated)
                                {
                                    <li><a class="dropdown-item" asp-controller="Account" asp-action="Login">Iniciar Sesión</a></li>
                                }
                                else
                                {
                                    <li><a class="dropdown-item" asp-controller="Account" asp-action="LogOut">Cerrar Sesión</a></li>
                                }
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2023 - PS MOSQUITO
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>